### ISSUE TITLE
what if the templates push folder contains other files and folders?

### ISSUE THREAD

**Issue by katlimruiz** [wildbit/postmark-cli#10]
If for example I have this structure
```
pm-templates
-- template1
---- content.html
---- meta.json
-- template2
---- content.html
---- meta.json
-- tmpstyles
---- 1.css
```
And I call the cli `postmark template push ./pm-templates`

What will the cli do with tmpstyles folder? ignore it? or try to push it?

**Comment by katlimruiz** [comment]
I already found the answer

in createManifest method, it verifies if there is a file called meta.json, so that will tell the cli to use that folder as a template or not.

**Comment by derekrushforth** [comment]
> in createManifest method, it verifies if there is a file called meta.json, so that will tell the cli to use that folder as a template or not.

@katlimruiz Yep, that's correct. Let me know if I can help with anything.
