### ISSUE TITLE
Modifies all templates during each push

### ISSUE THREAD

**Issue by pbrewton** [wildbit/postmark-cli#14]
"postmark templates push <folder>" appears to push every template each time that command is executed. All templates are marked "Modified" regardless if they were modified since the last push or not.

Is this by design or a bug?

**Comment by derekrushforth** [comment]
@pbrewton Yeah, this was by design, at least for now. It's definitely possible to compare the HTML/Text contents between both template versions. But this adds a lot more overhead, especially if you have a lot of templates on your server.

I'd love to look into this, so I'll add it as an enhancement.

**Comment by pbrewton** [comment]
Thanks for looking into this and considering the enhancement. 

We have approx 100 templates.  Is there a risk if it re-pushes all of those templates each time only 1 or a few were actually changed? I'm concerned about corrupting any of those templates with the repetitive uploads, especially since they were not intended to be part of the changeset, therefor likely wouldn't get tested after each push, etc.

Alternatively, is it possible to specify individual files to push? We could then perform our own version control and push selective templates.

**Comment by yardensachs** [comment]
This would be great for our CI/CD pipeline, so we can tell what was updated and what was not.
We have 100+ templates and it would be very helpful.

**Comment by derekrushforth** [comment]
This is now available in v1.5.8. More details in the [release notes](https://github.com/wildbit/postmark-cli/releases/tag/1.5.8).
