### ISSUE TITLE
Installation fails.

### ISSUE THREAD

**Issue by weisisheng** [wildbit/postmark-cli#23]
After d'loading from npm, using "postmark" command raises error on Ubuntu 19.04 saying to install postmark using apt get but the referenced package is completely different.

Node.js: 12.16.1, npm 6.13.4 

Please advise.  Thanks.

**Comment by derekrushforth** [comment]
@weisisheng can you paste your console logs? What do you see when running `which postmark`?

**Comment by weisisheng** [comment]
Thanks for the checking...

 npm i postmark-cli -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/home/foo/.nvm/versions/node/v10.14.1/bin/postmark -> /home/foo/.nvm/versions/node/v10.14.1/lib/node_modules/postmark-cli/dist/index.js
+ postmark-cli@1.4.7
added 3 packages from 7 contributors, removed 1 package and updated 10 packages in 74.593s
foo@foo:~$ which postmark (shows nothing)
foo@foo:~$

then-->

$ postmark

Command 'postmark' not found, but can be installed with:

sudo apt install postmark

***this does not install the right "postmark"

**Comment by weisisheng** [comment]
I probably angered the node.js gods but installing with sudo on ubuntu 19.04 worked.  Thanks!

**Comment by derekrushforth** [comment]
Got it. Thanks for the update!
