### ISSUE TITLE
Meta.json's "TestRenderModel" is not pushed with templates

### ISSUE THREAD

**Issue by mattjennings** [wildbit/postmark-cli#25]
I'd like to include some default test data in the `TestRenderModel` of a template's meta.json, however it isn't kept when I push my templates. Instead, it's replaced with:

```json
{
	"company": {
		"primaryColor": "primaryColor_Value",
		"logo": "logo_Value",
		"name": "name_Value"
	},
	"body": "body_Value",
	"product_name": "product_name_Value",
	"product_url": "product_url_Value",
	"bodyText": "bodyText_Value",
	"company_name": "company_name_Value",
	"company_address": "company_address_Value",
	"subject": "subject_Value"
}
```

The "company" field is our own custom properties we've added. We don't use the others, and have removed them from the template, yet they come back. If we then pull the templates our meta.json gets overwritten with the default data again.

**Comment by derekrushforth** [comment]
Hey @mattjennings, can you send me both the HTML and Text version of the template that's giving you trouble? You can email it to [derek@wildbit.com](mailto:derek@wildbit.com).

And by pull, do you mean pulling via the `postmark templates pull` command or git?

**Comment by mattjennings** [comment]
Correct! I'll email them to you.

**Comment by derekrushforth** [comment]
Closing this since we touched base via email. Thanks @mattjennings!
