### ISSUE TITLE
Templates preview - add dark mode button

### ISSUE THREAD

**Issue by arlukin** [wildbit/postmark-cli#28]
On the webpage generated by "postmark templates preview" it would be nice with a button that can switch to dark mode and back to normal.

The subject at the footer on the same webpage. It would be nice if meta data would be converted.

**Comment by derekrushforth** [comment]
> On the webpage generated by "postmark templates preview" it would be nice with a button that can switch to dark mode and back to normal.

I wish we could do this, but it's not possible. Most templates (including ours) use the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media query for specifying dark mode styles. This property looks at the system preferences to determine which appearance mode to use and as of right now there is no way to override this at the browser level. 

> The subject at the footer on the same webpage. It would be nice if meta data would be converted.

I'll look into this!

**Comment by derekrushforth** [comment]
@arlukin Subject line renderings are now available in v1.5.8. Check out the [release notes](https://github.com/wildbit/postmark-cli/releases/tag/1.5.8) for more details.

I did some more research and it still isn't possible to force dark mode on templates via the `prefers-colo-scheme` CSS media query. Closing this issue.
