### ISSUE TITLE
Minor cli output formatting issue

### ISSUE THREAD

**Issue by cybercode** [wildbit/postmark-cli#31]
Love the tool. Since you seemed to have worked so hard on the terminal output formatting, I though you might like to fix this (minor) visual annoyance:

There should be whitespace between the icon and the string  in `✅All finished!`:

<img width="460" alt="Screen Shot 2020-07-13 at 8 31 26 AM" src="https://user-images.githubusercontent.com/279708/87318356-39445580-c4f6-11ea-819c-d6658ae8bc31.png">

**Comment by derekrushforth** [comment]
Thanks @cybercode. I'll take care of this one!

**Comment by derekrushforth** [comment]
@cybercode, It looks like there's [already whitespace](https://github.com/wildbit/postmark-cli/blame/master/src/commands/templates/push.ts#L310) in between the emoji and the text. I also tested this on iTerm and Terminal in MacOS 11.01 and am not seeing the same formatting issue.

<img width="570" alt="Screen Shot 2020-12-09 at 8 17 31 AM" src="https://user-images.githubusercontent.com/3054417/101648856-7bb38500-39f7-11eb-8508-132ef490a83e.png">

Closing this one. If we see more issues I will consider removing all the emojis from the output.
