### ISSUE TITLE
Unable to reliably update templates when more than 100 templates exist.

### ISSUE THREAD

**Issue by paul-millar** [wildbit/postmark-cli#33]
We're big fans of Mailmason and Postmark at Yarno - but have ran into issues updating our templates...

For context, we have 26 'email templates' which we compile with different layouts to achieve differently branded emails (white labelling). We compile these on a CI server that essentially swaps out `THEME` pre-run. Eg:

```json
{
  "Name": "welcome_email - THEME",
  "Alias": "welcome_email__THEME",
  "Subject": "{{preheader}}",
  "TemplateType": "Standard",
  "LayoutTemplate": "THEME"
}
```

becomes:
```json
{
  "Name": "welcome_email - yarno",
  "Alias": "welcome_email__yarno",
  "Subject": "{{preheader}}",
  "TemplateType": "Standard",
  "LayoutTemplate": "yarno"
}
```

At the end of our CI run, we have a folder for each `THEME` and this results in seperate templates like:
```
welcome_email__yarno
welcome_email__company_a
welcome_email__company_b
```

As a result, we currently have 156 templates that exist on our postmark account (that are generated from the 26 mailmaison templates).

When pushing templates, we're now unable to push up all templates reliably as we're met with multiple errors like:
```
yarno: ApiInputError: The specified alias is already in use by another template or layout.
``` 

This appears to be tied to the fact that when the CLI runs, it thinks that some of the templates are new (as opposed to old ones that need to be updated). I traced this back to the following, which will only return 100 templates max and not utilise the pagination / count:
https://github.com/wildbit/postmark-cli/blob/4f395bdce4f67e336447e3db2fe312216d09e90f/src/commands/templates/push.ts#L84-L85

I did read that [we're able to push up to 100 templates at a time](https://postmarkapp.com/support/article/1100-templates-faq), but I assumed that this was tied up in pushing templates up each time (and thought I would be good given we push up 26 templates in each CLI use). Rather, it looks like it breaks the minute you go over 100 templates on the account. I appreciate this is what this article might have actually been referring to though!

**Comment by paul-millar** [comment]
https://github.com/wildbit/postmark-cli/commit/b153e8357fe362a382bbdeeea2bf7d7615ccce7d [Thanks](https://youtu.be/OcfqDPAy7zc?t=6)

**Comment by derekrushforth** [comment]
Hey @paul-millar, this one fell off my radar. Apologies for the late response. Whoa, sounds like you've got an awesome setup for managing multiple themes!

Did the template limit increase fix your issue? I'm curious whether you're still seeing the error saying that the alias is already in use. That seems like this would be unrelated to upping the limit.

**Comment by paul-millar** [comment]
> Hey @paul-millar, this one fell off my radar. Apologies for the late response. Whoa, sounds like you've got an awesome setup for managing multiple themes!
> 
> Did the template limit increase fix your issue? I'm curious whether you're still seeing the error saying that the alias is already in use. That seems like this would be unrelated to upping the limit.

Not at all - I would be lying if I said I didn't do this on a frequent basis! 

The template limit increase did indeed fix the issue. From my understanding, this manifests as the `ApiInputError` above as the postmark-cli was only aware of the 100 templates it pulled. As a result, when it loops over all of the templates in the directory (to push), it will assume that the template is new rather than one that needs to be updated and calls `createTemplate` rather than `editTemplate` - resulting in the ApiInputError. Hope that makes sense. 

Thanks again!

**Comment by derekrushforth** [comment]
Thanks for clarifying @paul-millar! Closing this since your issue is fixed now.
