### ISSUE TITLE
Pushing templates to server without existing templates

### ISSUE THREAD

**Issue by webkp** [wildbit/postmark-cli#40]
Hi! 

I started working with postmark-cli to make it work with CI/CD (thanks for this great tool!).
However, I noticed that no push is performed if the server does not have any templates yet. It doesn't matter if you use additional parameters like ```-force``` and/or ```-all```. Only "Fetching templates" is returned and then the process is terminated.

```
/app # postmark templates push . -force
- Fetching templates...
```

I think when a server is empty, all templates should actually be uploaded. Especially if ```-force``` is used.

**Comment by derekrushforth** [comment]
Thanks for the heads up @webkp! I just published a fix for this in version `1.5.9`. Give it a shot and let me know if it's fixed on your end.

**Comment by webkp** [comment]
Thank you for this quick fix @derekrushforth. Now it's working as expected.

**Comment by derekrushforth** [comment]
@webkp Awesome! Closing this issue.
