### ISSUE TITLE
Add --reply-to parameter

### ISSUE THREAD

**Issue by h** [wildbit/postmark-cli#70]
The postmark-cli library currently doesn't expose a command-line parameter for setting the ReplyTo header for the email. We'd like to add a `--reply-to` parameter that does this.

**Comment by h** [comment]
This is implemented in PR #68 . Could you please review the PR and merge if it looks good for inclusion in the libarary?

**Comment by tomek-ac** [comment]
This doesn't seem to have much interest. Closing for now.
